# Classification Dataset

In [2]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

raindata = pd.read_csv("C:/Users/rushi/OneDrive/Desktop/Projects DS,ML,DL,AI/Analysis of mumbai weather-Classification/rainfall.csv")
raindata

datetime  temp   dew  humidity  sealevelpressure  winddir  \
0     01-01-2016  28.4  11.9      37.8            1016.4    147.5   
1     02-01-2016  26.8  13.0      44.8            1017.2    110.3   
2     03-01-2016  25.5  14.6      52.8            1015.7    145.3   
3     04-01-2016  26.4  13.1      46.6            1015.3    126.9   
4     05-01-2016  27.1  13.5      44.9            1014.4    125.5   
...          ...   ...   ...       ...               ...      ...   
1776  11-11-2020  27.4  12.2      41.5            1011.8    108.3   
1777  12-11-2020  28.0  13.0      40.9            1012.6    148.4   
1778  13-11-2020  28.4  18.7      56.9            1011.9    131.8   
1779  14-11-2020  29.5  20.9      61.3            1010.2    154.2   
1780  15-11-2020  29.7  22.3      65.4            1010.7    150.5   

      solarradiation  windspeed  precipprob  preciptype  
0              216.1       16.6           0           0  
1              215.7       16.6           0           0  
2              221.1       18.4           0           0  
3              216.2       16.6           0           0  
4              208.1       16.6           0           0  
...              ...        ...         ...         ...  
1776           220.4       17.2           0           0  
1777           225.1       16.6           0           0  
1778           223.4       18.4           0           0  
1779           232.7       19.3           0           0  
1780           225.9       17.1           0           0  

[1781 rows x 10 columns]

In [23]:
x = raindata.iloc[:,[1,3]].values
y = raindata.iloc[:,8].values

In [24]:
x[:10]


array([[28.4, 37.8],
       [26.8, 44.8],
       [25.5, 52.8],
       [26.4, 46.6],
       [27.1, 44.9],
       [26.9, 48.2],
       [26.1, 58. ],
       [26.6, 55.2],
       [26.3, 47.6],
       [26. , 45.3]])

In [25]:
y[:10]

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0], dtype=int64)

In [26]:
from sklearn.model_selection import train_test_split
xtrain, xtest, ytrain, ytest = train_test_split(x, y, test_size = 0.20, random_state = 0)

In [27]:
xtrain

array([[26.8, 55.9],
       [30.5, 40.6],
       [27.9, 49.6],
       ...,
       [29.4, 85.7],
       [28.6, 82.9],
       [27.9, 51.6]])

In [28]:
xtest

array([[28.2, 86.4],
       [29.2, 68.5],
       [28.4, 71.7],
       [27.3, 85. ],
       [28.5, 83.8],
       [26.8, 68.8],
       [31.8, 71.3],
       [31.5, 72.7],
       [28.5, 78.4],
       [25.9, 92.9],
       [29.4, 73. ],
       [29.3, 68.5],
       [30. , 79.7],
       [25.8, 94.8],
       [28. , 40.7],
       [29.4, 68.4],
       [29. , 72.7],
       [29.7, 65.4],
       [29.6, 84.1],
       [29.1, 84.9],
       [31.4, 74.8],
       [25.2, 67.3],
       [29. , 48.9],
       [26.1, 58. ],
       [30.1, 82.6],
       [29. , 85.5],
       [27.9, 86.7],
       [23.9, 65.8],
       [29.7, 78. ],
       [31.3, 73.8],
       [29.7, 76.9],
       [30.7, 65.5],
       [21.7, 35.4],
       [23.3, 91.2],
       [30.4, 75.7],
       [26.9, 90.3],
       [28.6, 81. ],
       [23.6, 58.8],
       [29.3, 69.5],
       [28.5, 82. ],
       [31.2, 60.1],
       [31.2, 70.3],
       [30.8, 40.1],
       [28.6, 56.5],
       [30.9, 72.5],
       [24.3, 63.8],
       [27.1, 46.2],
       [28.8,

In [29]:
len(xtrain)

1424

In [30]:
len(xtest)

357

In [31]:
ytrain

array([  0,   0,   0, ..., 100, 100,   0], dtype=int64)

In [32]:
ytest

array([100, 100,   0, 100, 100,   0, 100,   0, 100, 100,   0, 100, 100,
       100,   0,   0,   0,   0, 100, 100, 100, 100,   0,   0, 100, 100,
       100,   0, 100, 100, 100,   0,   0, 100,   0, 100, 100,   0, 100,
       100,   0,   0,   0,   0, 100,   0,   0, 100, 100,   0, 100,   0,
         0,   0, 100, 100,   0, 100,   0,   0, 100,   0,   0,   0, 100,
       100,   0,   0, 100,   0, 100,   0,   0,   0, 100,   0, 100, 100,
         0,   0, 100, 100, 100, 100, 100,   0,   0, 100,   0, 100, 100,
       100,   0, 100,   0, 100,   0, 100,   0,   0,   0,   0,   0, 100,
         0,   0,   0, 100,   0,   0,   0,   0,   0, 100, 100,   0, 100,
       100, 100, 100,   0,   0, 100, 100, 100, 100,   0, 100,   0, 100,
       100,   0,   0, 100,   0,   0, 100,   0, 100,   0, 100, 100,   0,
         0,   0, 100, 100, 100, 100,   0,   0,   0,   0, 100, 100,   0,
       100,   0,   0, 100,   0, 100, 100, 100, 100,   0,   0, 100, 100,
       100,   0,   0, 100, 100, 100,   0,   0,   0,   0,   0, 10

In [33]:
len(ytrain)

1424

In [34]:
len(xtest)

357

In [43]:
from sklearn.preprocessing import StandardScaler
sc_x =StandardScaler()
xtrain = sc_x.fit_transform(xtrain)
xtest = sc_x.transform(xtest)

print(xtrain[0:10])

[[-0.79408946 -0.92480692]
 [ 1.1045757  -1.98057719]
 [-0.22962144 -1.35953586]
 [ 0.38616185  0.64159734]
 [ 0.02695493  1.01422214]
 [-0.99935055 -0.97311014]
 [ 0.84799932 -1.55274872]
 [ 1.00194515 -0.73849452]
 [-2.07697132 -1.73906112]
 [-4.18089757 -1.24222805]]


# Logistic Regression Model

In [36]:
from sklearn.linear_model import LogisticRegression
classifier = LogisticRegression(random_state = 0)
classifier.fit(xtrain, ytrain)

LogisticRegression(random_state=0)

In [37]:
xtest

array([[-7.56756153e-02,  1.17983317e+00],
       [ 4.37477129e-01, -5.53490492e-02],
       [ 2.69549335e-02,  1.65465648e-01],
       [-5.37513085e-01,  1.08322673e+00],
       [ 7.82702079e-02,  1.00042122e+00],
       [-7.94089457e-01, -3.46476713e-02],
       [ 1.77167426e+00,  1.37863811e-01],
       [ 1.61772844e+00,  2.34470241e-01],
       [ 7.82702079e-02,  6.27796421e-01],
       [-1.25592693e+00,  1.62836302e+00],
       [ 5.40107677e-01,  2.55171619e-01],
       [ 4.88792403e-01, -5.53490492e-02],
       [ 8.47999324e-01,  7.17502392e-01],
       [-1.30724220e+00,  1.75947175e+00],
       [-1.78306164e-01, -1.97367673e+00],
       [ 5.40107677e-01, -6.22495085e-02],
       [ 3.34846580e-01,  2.34470241e-01],
       [ 6.94053501e-01, -2.69263287e-01],
       [ 6.42738226e-01,  1.02112260e+00],
       [ 3.86161854e-01,  1.07632628e+00],
       [ 1.56641317e+00,  3.79379887e-01],
       [-1.61513385e+00, -1.38154561e-01],
       [ 3.34846580e-01, -1.40783907e+00],
       [-1.

In [38]:
y_pred = classifier.predict(xtest)
y_pred

array([100,   0,   0, 100, 100,   0, 100, 100, 100, 100, 100,   0, 100,
       100,   0,   0,   0,   0, 100, 100, 100,   0,   0,   0, 100, 100,
       100,   0, 100, 100, 100,   0,   0, 100, 100, 100, 100,   0,   0,
       100,   0,   0,   0,   0, 100,   0,   0, 100, 100,   0, 100,   0,
         0, 100, 100, 100, 100, 100,   0,   0, 100,   0,   0,   0, 100,
       100,   0,   0, 100,   0, 100,   0, 100, 100,   0, 100,   0, 100,
         0,   0, 100, 100,   0, 100, 100,   0, 100, 100,   0, 100, 100,
       100,   0,   0,   0, 100,   0, 100,   0,   0,   0,   0,   0, 100,
         0,   0,   0, 100,   0, 100,   0, 100,   0, 100, 100,   0, 100,
         0, 100, 100,   0,   0, 100, 100, 100, 100,   0, 100, 100, 100,
       100,   0,   0, 100,   0,   0, 100,   0, 100,   0, 100,   0, 100,
         0,   0, 100, 100, 100,   0,   0, 100,   0,   0, 100, 100,   0,
       100,   0,   0, 100,   0, 100, 100, 100, 100,   0,   0, 100, 100,
       100,   0,   0, 100, 100, 100,   0,   0,   0,   0, 100, 10

In [39]:
ytest

array([100, 100,   0, 100, 100,   0, 100,   0, 100, 100,   0, 100, 100,
       100,   0,   0,   0,   0, 100, 100, 100, 100,   0,   0, 100, 100,
       100,   0, 100, 100, 100,   0,   0, 100,   0, 100, 100,   0, 100,
       100,   0,   0,   0,   0, 100,   0,   0, 100, 100,   0, 100,   0,
         0,   0, 100, 100,   0, 100,   0,   0, 100,   0,   0,   0, 100,
       100,   0,   0, 100,   0, 100,   0,   0,   0, 100,   0, 100, 100,
         0,   0, 100, 100, 100, 100, 100,   0,   0, 100,   0, 100, 100,
       100,   0, 100,   0, 100,   0, 100,   0,   0,   0,   0,   0, 100,
         0,   0,   0, 100,   0,   0,   0,   0,   0, 100, 100,   0, 100,
       100, 100, 100,   0,   0, 100, 100, 100, 100,   0, 100,   0, 100,
       100,   0,   0, 100,   0,   0, 100,   0, 100,   0, 100, 100,   0,
         0,   0, 100, 100, 100, 100,   0,   0,   0,   0, 100, 100,   0,
       100,   0,   0, 100,   0, 100, 100, 100, 100,   0,   0, 100, 100,
       100,   0,   0, 100, 100, 100,   0,   0,   0,   0,   0, 10

In [40]:
from sklearn.metrics import confusion_matrix
cm = confusion_matrix(ytest, y_pred)

print("Confusion Matrix : \n", cm)

Confusion Matrix : 
 [[154  27]
 [ 22 154]]


In [41]:
from sklearn.metrics import accuracy_score
print("Accuracy : ",accuracy_score(ytest,y_pred))

Accuracy :  0.8627450980392157


# K-NN model

In [45]:
from sklearn.neighbors import KNeighborsClassifier
classifier = KNeighborsClassifier(n_neighbors=10, metric='minkowski',p=2)
classifier.fit(xtrain,ytrain)

KNeighborsClassifier(n_neighbors=10)

In [47]:
y_pred = classifier.predict(xtest)
y_pred

array([100,   0,   0, 100, 100,   0,   0, 100, 100, 100,   0,   0, 100,
       100,   0,   0,   0,   0, 100, 100, 100,   0,   0,   0, 100, 100,
       100,   0, 100, 100, 100,   0,   0, 100, 100, 100, 100,   0,   0,
       100,   0,   0,   0,   0,   0,   0,   0,   0, 100,   0, 100,   0,
         0,   0, 100, 100,   0, 100,   0,   0, 100,   0,   0,   0, 100,
       100,   0,   0, 100,   0, 100,   0,   0,   0,   0,   0,   0, 100,
         0,   0, 100, 100,   0,   0, 100,   0,   0, 100,   0, 100, 100,
       100, 100,   0,   0, 100,   0, 100,   0,   0,   0,   0,   0, 100,
         0,   0,   0, 100,   0,   0,   0,   0,   0, 100, 100,   0, 100,
         0, 100, 100,   0,   0, 100, 100, 100, 100,   0, 100, 100, 100,
         0,   0,   0,   0,   0,   0, 100,   0,   0,   0, 100, 100,   0,
         0,   0, 100, 100, 100,   0,   0, 100,   0,   0, 100, 100,   0,
       100,   0,   0, 100,   0, 100, 100, 100, 100,   0,   0,   0, 100,
       100,   0,   0, 100, 100, 100,   0,   0,   0,   0, 100, 10

In [51]:
from sklearn.metrics import confusion_matrix  
cm= confusion_matrix(ytest, y_pred)
cm

array([[172,   9],
       [ 36, 140]], dtype=int64)

In [52]:
from sklearn.metrics import accuracy_score
print("K-NN Accuracy : ",accuracy_score(ytest,y_pred))

K-NN Accuracy :  0.8739495798319328
